import os
import asyncio
from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup, Document
from telegram.ext import Application, CommandHandler, CallbackQueryHandler, MessageHandler, filters, ContextTypes, ConversationHandler
from telegram.constants import ParseMode
from dotenv import load_dotenv
from datetime import datetime
from io import BytesIO
import json

# Import file generation libraries
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle
from reportlab.lib import colors
from reportlab.lib.units import inch
from docx import Document as DocxDocument
from docx.shared import Pt, RGBColor, Inches
from pptx import Presentation
from pptx.util import Inches as PptxInches, Pt as PptxPt

load_dotenv()

BOT_TOKEN = os.getenv("BOT_TOKEN", "8625557628:AAHeUC2WxfMjJk-RRq3IxTtUJoc0H4XSsAM")
ADMIN_ID = int(os.getenv("ADMIN_ID", "7758296066"))

# States
CHOOSING_TYPE, CHOOSING_STYLE, CHOOSING_FORMAT, WRITING_TITLE, WRITING_CONTENT = range(5)

# Global storage
user_data_store = {}
documents_store = {}

# ==================== FILE GENERATION ====================

def generate_pdf(title, content, style, doc_type):
    """Generate PDF file"""
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=0.5*inch, bottomMargin=0.5*inch)
    
    styles = getSampleStyleSheet()
    story = []
    
    # Header
    header_style = ParagraphStyle(
        'CustomHeader',
        parent=styles['Heading1'],
        fontSize=16,
        textColor=colors.HexColor('#1f77b4'),
        spaceAfter=30,
        alignment=1
    )
    
    story.append(Paragraph(f"<b>{title}</b>", header_style))
    story.append(Spacer(1, 0.2*inch))
    
    # Metadata
    metadata = f"""
    <font size=10 color="#666666">
    <b>Hujjat Turi:</b> {doc_type}<br/>
    <b>Uslub:</b> {style}<br/>
    <b>Sana:</b> {datetime.now().strftime('%d.%m.%Y')}<br/>
    </font>
    """
    story.append(Paragraph(metadata, styles['Normal']))
    story.append(Spacer(1, 0.3*inch))
    
    # Content
    content_style = ParagraphStyle(
        'ContentStyle',
        parent=styles['Normal'],
        fontSize=11,
        alignment=4,
        spaceAfter=12
    )
    
    # Split content by paragraphs
    paragraphs = content.split('\n\n')
    for para in paragraphs:
        if para.strip():
            story.append(Paragraph(para.strip(), content_style))
            story.append(Spacer(1, 0.1*inch))
    
    # Footer
    story.append(Spacer(1, 0.5*inch))
    footer = """
    <font size=9 color="#999999">
    ================================================================<br/>
    Generated by Akadem Yordamchi Bot<br/>
    User ID: {} | Style: {} | Type: {}<br/>
    ================================================================
    """.format(ADMIN_ID, style, doc_type)
    story.append(Paragraph(footer, styles['Normal']))
    
    doc.build(story)
    buffer.seek(0)
    return buffer

def generate_docx(title, content, style, doc_type):
    """Generate DOCX file"""
    doc = DocxDocument()
    
    # Add title
    title_para = doc.add_paragraph()
    title_run = title_para.add_run(title)
    title_run.font.size = Pt(16)
    title_run.font.bold = True
    title_run.font.color.rgb = RGBColor(31, 119, 180)
    
    # Add metadata
    meta_para = doc.add_paragraph()
    meta_text = f"Hujjat Turi: {doc_type} | Uslub: {style} | Sana: {datetime.now().strftime('%d.%m.%Y')}"
    meta_run = meta_para.add_run(meta_text)
    meta_run.font.size = Pt(10)
    meta_run.font.color.rgb = RGBColor(100, 100, 100)
    
    doc.add_paragraph()  # Empty line
    
    # Add content
    for paragraph in content.split('\n\n'):
        if paragraph.strip():
            para = doc.add_paragraph(paragraph.strip(), style='Normal')
            for run in para.runs:
                run.font.size = Pt(11)
    
    # Add footer
    doc.add_paragraph()
    footer_para = doc.add_paragraph("=" * 60)
    footer_text = f"Generated by Akadem Yordamchi Bot | User ID: {ADMIN_ID}"
    footer_run = footer_para.add_run(footer_text)
    footer_run.font.size = Pt(9)
    footer_run.font.color.rgb = RGBColor(150, 150, 150)
    
    buffer = BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer

def generate_pptx(title, content, style, doc_type):
    """Generate PPTX (PowerPoint) file"""
    prs = Presentation()
    prs.slide_width = PptxInches(10)
    prs.slide_height = PptxInches(7.5)
    
    # Slide 1: Title
    slide1 = prs.slides.add_slide(prs.slide_layouts[6])  # Blank layout
    background = slide1.background
    fill = background.fill
    fill.solid()
    fill.fore_color.rgb = RGBColor(31, 119, 180)
    
    title_box = slide1.shapes.add_textbox(PptxInches(0.5), PptxInches(2.5), PptxInches(9), PptxInches(2))
    title_frame = title_box.text_frame
    title_frame.word_wrap = True
    title_p = title_frame.paragraphs[0]
    title_p.text = title
    title_p.font.size = PptxPt(44)
    title_p.font.bold = True
    title_p.font.color.rgb = RGBColor(255, 255, 255)
    
    # Slide 2: Metadata
    slide2 = prs.slides.add_slide(prs.slide_layouts[6])
    
    meta_box = slide2.shapes.add_textbox(PptxInches(1), PptxInches(1), PptxInches(8), PptxInches(2))
    meta_frame = meta_box.text_frame
    meta_text = f"Hujjat Turi: {doc_type}\nUslub: {style}\nSana: {datetime.now().strftime('%d.%m.%Y')}"
    meta_frame.text = meta_text
    for paragraph in meta_frame.paragraphs:
        paragraph.font.size = PptxPt(18)
    
    # Slide 3+: Content (split into chunks)
    content_per_slide = 300  # Characters per slide
    content_chunks = [content[i:i+content_per_slide] for i in range(0, len(content), content_per_slide)]
    
    for chunk in content_chunks:
        slide = prs.slides.add_slide(prs.slide_layouts[6])
        content_box = slide.shapes.add_textbox(PptxInches(0.5), PptxInches(0.5), PptxInches(9), PptxInches(6.5))
        content_frame = content_box.text_frame
        content_frame.word_wrap = True
        content_frame.text = chunk.strip()
        for paragraph in content_frame.paragraphs:
            paragraph.font.size = PptxPt(14)
    
    buffer = BytesIO()
    prs.save(buffer)
    buffer.seek(0)
    return buffer

# ==================== BOT HANDLERS ====================

async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Start command"""
    user_id = update.effective_user.id
    user_name = update.effective_user.first_name
    
    if user_id not in user_data_store:
        user_data_store[user_id] = {
            "name": user_name,
            "documents": 0,
            "created_at": datetime.now()
        }
    
    keyboard = [
        [
            InlineKeyboardButton("📝 Referat", callback_data="doc_referat"),
            InlineKeyboardButton("📚 Kurs Ishi", callback_data="doc_kurs")
        ],
        [
            InlineKeyboardButton("📄 Maqola", callback_data="doc_maqola"),
            InlineKeyboardButton("🎯 Slide", callback_data="doc_slide")
        ],
        [
            InlineKeyboardButton("📊 Statistika", callback_data="stats"),
            InlineKeyboardButton("❓ Yordam", callback_data="help")
        ]
    ]
    
    await update.message.reply_text(
        f"🎓 Assalomu alaykum, {user_name}!\n\n"
        "**Akademik Yordamchi Botga Xush Kelibsiz!**\n\n"
        "Siz quyidagi hujjatlarni yarata olasiz:\n"
        "📝 Referat - Kichik tadqiqot ishi\n"
        "📚 Kurs Ishi - Kurs oxirida topshirish\n"
        "📄 Maqola - Ilmiy maqola\n"
        "🎯 Slide - Prezentasiya\n\n"
        "💡 Birinchi hujjat TEKIN!",
        reply_markup=InlineKeyboardMarkup(keyboard),
        parse_mode=ParseMode.MARKDOWN
    )

async def handle_doc_type(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handle document type"""
    query = update.callback_query
    await query.answer()
    
    user_id = query.from_user.id
    doc_type = query.data.replace("doc_", "")
    
    if user_id not in user_data_store:
        user_data_store[user_id] = {}
    
    user_data_store[user_id]["doc_type"] = doc_type
    
    doc_types = {
        "referat": "📝 Referat",
        "kurs": "📚 Kurs Ishi",
        "maqola": "📄 Maqola",
        "slide": "🎯 Slide"
    }
    
    keyboard = [
        [
            InlineKeyboardButton("🎯 APA", callback_data="style_apa"),
            InlineKeyboardButton("🎯 Harvard", callback_data="style_harvard")
        ],
        [
            InlineKeyboardButton("🎯 Uzbek", callback_data="style_uzbek"),
            InlineKeyboardButton("🎯 Chicago", callback_data="style_chicago")
        ]
    ]
    
    await query.edit_message_text(
        f"✅ Siz {doc_types.get(doc_type)} turini tanladingiz\n\n"
        "📋 **Endi uslubni tanlang:**",
        reply_markup=InlineKeyboardMarkup(keyboard),
        parse_mode=ParseMode.MARKDOWN
    )

async def handle_style(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handle style selection"""
    query = update.callback_query
    await query.answer()
    
    user_id = query.from_user.id
    style = query.data.replace("style_", "")
    
    if user_id not in user_data_store:
        user_data_store[user_id] = {}
    
    user_data_store[user_id]["style"] = style
    
    styles = {
        "apa": "APA Style",
        "harvard": "Harvard Style",
        "uzbek": "O'zbek Standarti",
        "chicago": "Chicago Style"
    }
    
    keyboard = [
        [
            InlineKeyboardButton("📄 PDF", callback_data="format_pdf"),
            InlineKeyboardButton("📋 DOCX", callback_data="format_docx")
        ],
        [
            InlineKeyboardButton("🎯 PPTX", callback_data="format_pptx")
        ]
    ]
    
    await query.edit_message_text(
        f"✅ Siz {styles.get(style)} ni tanladingiz\n\n"
        "📄 **Fayl formatini tanlang:**",
        reply_markup=InlineKeyboardMarkup(keyboard),
        parse_mode=ParseMode.MARKDOWN
    )

async def handle_format(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handle format selection"""
    query = update.callback_query
    await query.answer()
    
    user_id = query.from_user.id
    file_format = query.data.replace("format_", "")
    
    if user_id not in user_data_store:
        user_data_store[user_id] = {}
    
    user_data_store[user_id]["format"] = file_format
    
    await query.edit_message_text(
        "✏️ **Hujjatning sarlavhasini yuboring:**\n\n"
        "_Misol: \"Kimyo texnologiyasi va IT\"_"
    )
    
    context.user_data[user_id] = {"state": "title"}

async def handle_message(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handle messages"""
    user_id = update.effective_user.id
    text = update.message.text
    
    if user_id not in context.user_data:
        context.user_data[user_id] = {}
    
    state = context.user_data[user_id].get("state")
    
    if state == "title":
        if user_id not in user_data_store:
            user_data_store[user_id] = {}
        
        user_data_store[user_id]["title"] = text
        context.user_data[user_id]["state"] = "content"
        
        await update.message.reply_text(
            f"✅ Sarlavha qabul qilindi: **{text}**\n\n"
            "📝 **Endi matnni yuboring:**\n\n"
            "_Uzun bo'lsa, bir nechta xabarda yuboring._"
        )
    
    elif state == "content":
        if user_id not in user_data_store:
            user_data_store[user_id] = {}
        
        if "content" in user_data_store[user_id]:
            user_data_store[user_id]["content"] += "\n\n" + text
        else:
            user_data_store[user_id]["content"] = text
        
        char_count = len(user_data_store[user_id]["content"])
        word_count = len(user_data_store[user_id]["content"].split())
        
        keyboard = [
            [InlineKeyboardButton("✅ Tugatish va Fayl Olish", callback_data="finish_doc")],
            [InlineKeyboardButton("➕ Yana Matn Qo'shish", callback_data="add_more")],
            [InlineKeyboardButton("❌ Bekor Qilish", callback_data="cancel_doc")]
        ]
        
        await update.message.reply_text(
            f"✅ **Matn Qabul Qilindi!**\n\n"
            f"📊 **Statistika:**\n"
            f"   • Belgisiz: {char_count}\n"
            f"   • So'zlar: {word_count}\n\n"
            f"🔄 **Quyidagini Tanlang:**",
            reply_markup=InlineKeyboardMarkup(keyboard),
            parse_mode=ParseMode.MARKDOWN
        )

async def finish_document(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Finish and generate document"""
    query = update.callback_query
    await query.answer()
    
    user_id = query.from_user.id
    
    if user_id not in user_data_store:
        await query.edit_message_text("❌ Xato sodir bo'ldi!")
        return
    
    doc_data = user_data_store[user_id]
    title = doc_data.get("title", "Hujjat")
    content = doc_data.get("content", "")
    style = doc_data.get("style", "APA")
    doc_type = doc_data.get("doc_type", "Referat")
    file_format = doc_data.get("format", "pdf")
    
    try:
        await query.edit_message_text("⏳ Hujjat tayyorlanmoqda...")
        
        # Generate file based on format
        if file_format == "pdf":
            file_buffer = generate_pdf(title, content, style, doc_type)
            filename = f"{title.replace(' ', '_')}.pdf"
            mime_type = "application/pdf"
        elif file_format == "docx":
            file_buffer = generate_docx(title, content, style, doc_type)
            filename = f"{title.replace(' ', '_')}.docx"
            mime_type = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
        elif file_format == "pptx":
            file_buffer = generate_pptx(title, content, style, doc_type)
            filename = f"{title.replace(' ', '_')}.pptx"
            mime_type = "application/vnd.openxmlformats-officedocument.presentationml.presentation"
        
        # Send file
        await context.bot.send_document(
            chat_id=user_id,
            document=file_buffer,
            filename=filename
        )
        
        # Update statistics
        if user_id in user_data_store:
            user_data_store[user_id]["documents"] = user_data_store[user_id].get("documents", 0) + 1
        
        # Show success message
        keyboard = [
            [InlineKeyboardButton("📝 Yangi Hujjat", callback_data="new_doc")],
            [InlineKeyboardButton("📊 Statistika", callback_data="stats")],
            [InlineKeyboardButton("🏠 Bosh Menyu", callback_data="start")]
        ]
        
        await context.bot.send_message(
            chat_id=user_id,
            text=f"✅ **Hujjat Tayyorlandi va Yuborildi!**\n\n"
                 f"📝 Tur: {doc_type}\n"
                 f"📋 Uslub: {style}\n"
                 f"📄 Format: {file_format.upper()}\n\n"
                 f"🎁 Birinchi hujjat tekin edi!",
            reply_markup=InlineKeyboardMarkup(keyboard),
            parse_mode=ParseMode.MARKDOWN
        )
        
        # Clear user data
        context.user_data[user_id]["state"] = None
        
    except Exception as e:
        print(f"Error: {e}")
        await context.bot.send_message(chat_id=user_id, text=f"❌ Xato: {str(e)}")

async def add_more(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Add more content"""
    query = update.callback_query
    await query.answer()
    
    user_id = query.from_user.id
    if user_id in context.user_data:
        context.user_data[user_id]["state"] = "content"
    
    await query.edit_message_text("📝 **Yana Matnni Yuboring:**")

async def cancel_doc(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Cancel document"""
    query = update.callback_query
    await query.answer()
    
    user_id = query.from_user.id
    if user_id in context.user_data:
        del context.user_data[user_id]
    
    keyboard = [
        [
            InlineKeyboardButton("📝 Referat", callback_data="doc_referat"),
            InlineKeyboardButton("📚 Kurs Ishi", callback_data="doc_kurs")
        ],
        [
            InlineKeyboardButton("📄 Maqola", callback_data="doc_maqola"),
            InlineKeyboardButton("🎯 Slide", callback_data="doc_slide")
        ]
    ]
    
    await query.edit_message_text(
        "❌ **Hujjat yaratilishi bekor qilindi!**\n\n"
        "Yangi hujjat yaratmoqchimisiz?",
        reply_markup=InlineKeyboardMarkup(keyboard)
    )

async def new_doc(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """New document"""
    query = update.callback_query
    await query.answer()
    
    keyboard = [
        [
            InlineKeyboardButton("📝 Referat", callback_data="doc_referat"),
            InlineKeyboardButton("📚 Kurs Ishi", callback_data="doc_kurs")
        ],
        [
            InlineKeyboardButton("📄 Maqola", callback_data="doc_maqola"),
            InlineKeyboardButton("🎯 Slide", callback_data="doc_slide")
        ]
    ]
    
    await query.edit_message_text(
        "🎓 **Hujjat turini tanlang:**",
        reply_markup=InlineKeyboardMarkup(keyboard)
    )

async def handle_stats(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Statistics"""
    query = update.callback_query
    await query.answer()
    
    user_id = query.from_user.id
    user_info = user_data_store.get(user_id, {})
    
    text = (
        f"📊 **SHAXSIY STATISTIKA**\n\n"
        f"👤 Ism: {user_info.get('name', 'Unknown')}\n"
        f"📄 Hujjatlar: {user_info.get('documents', 0)}\n"
        f"💾 User ID: {user_id}\n\n"
        f"✅ Bot ishga tushgan!"
    )
    
    keyboard = [
        [InlineKeyboardButton("📝 Yangi Hujjat", callback_data="new_doc")],
        [InlineKeyboardButton("🏠 Bosh Menyu", callback_data="start")]
    ]
    
    await query.edit_message_text(
        text,
        reply_markup=InlineKeyboardMarkup(keyboard),
        parse_mode=ParseMode.MARKDOWN
    )

async def handle_help(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Help"""
    query = update.callback_query
    await query.answer()
    
    text = (
        "📖 **Qo'llanma**\n\n"
        "1️⃣ Hujjat turini tanlang\n"
        "2️⃣ Uslubni tanlang (APA, Harvard, Uzbek, Chicago)\n"
        "3️⃣ Fayl formatini tanlang (PDF, DOCX, PPTX)\n"
        "4️⃣ Sarlavha yuboring\n"
        "5️⃣ Matnni yuboring\n"
        "6️⃣ Hujjat tayyor bo'ladi!\n\n"
        "💡 **Birinchi hujjat TEKIN!**\n\n"
        "📝 **Hujjat turlari:**\n"
        "• Referat - Kichik tadqiqot\n"
        "• Kurs Ishi - Kurs oxirida topshirish\n"
        "• Maqola - Ilmiy maqola\n"
        "• Slide - Prezentasiya"
    )
    
    keyboard = [
        [InlineKeyboardButton("📝 Boshlash", callback_data="new_doc")],
        [InlineKeyboardButton("🏠 Bosh Menyu", callback_data="start")]
    ]
    
    await query.edit_message_text(
        text,
        reply_markup=InlineKeyboardMarkup(keyboard),
        parse_mode=ParseMode.MARKDOWN
    )

async def handle_start_callback(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Start from callback"""
    query = update.callback_query
    await query.answer()
    
    keyboard = [
        [
            InlineKeyboardButton("📝 Referat", callback_data="doc_referat"),
            InlineKeyboardButton("📚 Kurs Ishi", callback_data="doc_kurs")
        ],
        [
            InlineKeyboardButton("📄 Maqola", callback_data="doc_maqola"),
            InlineKeyboardButton("🎯 Slide", callback_data="doc_slide")
        ],
        [
            InlineKeyboardButton("📊 Statistika", callback_data="stats"),
            InlineKeyboardButton("❓ Yordam", callback_data="help")
        ]
    ]
    
    await query.edit_message_text(
        "🎓 **Akademik Yordamchi Bot**\n\n"
        "Hujjat turini tanlang:",
        reply_markup=InlineKeyboardMarkup(keyboard),
        parse_mode=ParseMode.MARKDOWN
    )

async def help_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Help command"""
    keyboard = [
        [InlineKeyboardButton("📝 Boshlash", callback_data="new_doc")],
        [InlineKeyboardButton("🏠 Bosh Menyu", callback_data="start")]
    ]
    
    await update.message.reply_text(
        "📖 **Qo'llanma**\n\n"
        "/start - Botni boshlash\n"
        "/help - Yordam\n\n"
        "**Hujjat yaratish uchun:**\n"
        "1. Hujjat turini tanlang\n"
        "2. Uslubni tanlang\n"
        "3. Fayl formatini tanlang\n"
        "4. Sarlavha va matnni yuboring",
        reply_markup=InlineKeyboardMarkup(keyboard),
        parse_mode=ParseMode.MARKDOWN
    )

def main():
    """Start bot"""
    application = Application.builder().token(BOT_TOKEN).build()
    
    # Commands
    application.add_handler(CommandHandler("start", start))
    application.add_handler(CommandHandler("help", help_command))
    
    # Callbacks
    application.add_handler(CallbackQueryHandler(handle_doc_type, pattern="^doc_"))
    application.add_handler(CallbackQueryHandler(handle_style, pattern="^style_"))
    application.add_handler(CallbackQueryHandler(handle_format, pattern="^format_"))
    application.add_handler(CallbackQueryHandler(finish_document, pattern="^finish_doc$"))
    application.add_handler(CallbackQueryHandler(add_more, pattern="^add_more$"))
    application.add_handler(CallbackQueryHandler(cancel_doc, pattern="^cancel_doc$"))
    application.add_handler(CallbackQueryHandler(new_doc, pattern="^new_doc$"))
    application.add_handler(CallbackQueryHandler(handle_stats, pattern="^stats$"))
    application.add_handler(CallbackQueryHandler(handle_help, pattern="^help$"))
    application.add_handler(CallbackQueryHandler(handle_start_callback, pattern="^start$"))
    
    # Messages
    application.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle_message))
    
    print("✅ BOT ISHGA TUSHDI!")
    print("🚀 FILE GENERATION ACTIVE!")
    print("📄 PDF, DOCX, PPTX SUPPORT!")
    
    application.run_polling()

if __name__ == "__main__":
    main()
